// Project template generator. Produces the source files for a standalone
// Next.js app that mirrors the runtime's rendering of the given config.

import type { AppConfig } from '../config/types';

interface Opts { config: AppConfig; name: string; slug: string }

export function generateProjectFiles({ config, name, slug }: Opts) {
  const safeConfig = JSON.stringify(config, null, 2);
  const readme = `# ${name}

This app was generated by the App Generator.

## Run locally

\`\`\`bash
npm install
cp .env.example .env
npx prisma db push
npm run dev
\`\`\`

Open http://localhost:3000.

The dynamic runtime lives in \`lib/runtime\` and reads \`app.config.json\`.
`;
  const packageJson = `{
  "name": ${JSON.stringify(slug)},
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.18",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }
}
`;
  const nextConfig = `/** @type {import('next').NextConfig} */
module.exports = { reactStrictMode: true };
`;
  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = { content: ['./app/**/*.{ts,tsx}'], theme: { extend: {} }, plugins: [] };
`;
  const layout = `import './globals.css';
export const metadata = { title: ${JSON.stringify(name)} };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body className="min-h-screen bg-slate-50 text-slate-900">{children}</body></html>;
}
`;
  const globals = `@tailwind base; @tailwind components; @tailwind utilities;`;
  const page = `import { getServerConfig } from '@/lib/runtime/config';
import { Runtime } from '@/lib/runtime/Runtime';
export default function Home() {
  const config = getServerConfig();
  return <Runtime config={config} />;
}
`;
  // The runtime is the same renderer we already built. We serialize it.
  const runtimeFiles = buildRuntimeBundle();
  const envExample = `DATABASE_URL="postgresql://..."
NEXTAUTH_SECRET="change-me"
`;
  return [
    { path: 'README.md', content: readme },
    { path: 'package.json', content: packageJson },
    { path: 'next.config.js', content: nextConfig },
    { path: 'tailwind.config.js', content: tailwindConfig },
    { path: 'app/layout.tsx', content: layout },
    { path: 'app/globals.css', content: globals },
    { path: 'app/page.tsx', content: page },
    { path: 'app.config.json', content: safeConfig },
    { path: '.env.example', content: envExample },
    ...runtimeFiles,
  ];
}

function buildRuntimeBundle() {
  // The runtime used by the exported app. We point the exporter at the
  // actual source files in this repo (relative paths). Octokit will read
  // them at export time and inline them as text into the new repo.
  // For a real product you'd inline the bundled JS; for the export, we
  // copy the same renderer source into the generated repo.
  const fs = require('fs') as typeof import('fs');
  const path = require('path') as typeof import('path');
  const root = path.join(process.cwd(), 'components', 'renderer');
  const libRoot = path.join(process.cwd(), 'lib', 'config');
  const out: Array<{ path: string; content: string }> = [];
  function walk(dir: string, prefix: string) {
    for (const name of fs.readdirSync(dir)) {
      const full = path.join(dir, name);
      const stat = fs.statSync(full);
      if (stat.isDirectory()) walk(full, prefix + name + '/');
      else out.push({ path: prefix + name, content: fs.readFileSync(full, 'utf8') });
    }
  }
  try { walk(root, 'lib/runtime/renderer/'); } catch (e) { console.error('[export] renderer copy failed', e); }
  try { walk(libRoot, 'lib/runtime/config/'); } catch {}
  // Add a tiny entry that re-exports the renderer.
  out.push({
    path: 'lib/runtime/Runtime.tsx',
    content: `'use client';
import { Renderer } from './renderer/Renderer';
import { parseConfig } from './config/parser';
import { setI18nContext } from './renderer/useT';
import type { AppConfig } from './config/types';
export function Runtime({ config }: { config: AppConfig }) {
  const safe = parseConfig(config);
  setI18nContext({ i18n: safe.i18n, locale: 'en' });
  const home = safe.pages.find((p) => p.route === '/') ?? safe.pages[0];
  if (!home) return <div className="p-6">No pages.</div>;
  return <div className="max-w-5xl mx-auto p-6"><Renderer node={home.root} appId="local" /></div>;
}
`,
  });
  out.push({
    path: 'lib/runtime/config.ts',
    content: `import fs from 'fs'; import path from 'path';
import { parseConfig } from './config/parser';
export function getServerConfig() {
  const p = path.join(process.cwd(), 'app.config.json');
  return parseConfig(JSON.parse(fs.readFileSync(p, 'utf8')));
}
`,
  });
  return out;
}
