// GitHub export: creates a repo with the app's generated code.
// Uses the user's stored GitHub access token if available, otherwise falls
// back to a server-level GITHUB_EXPORT_TOKEN. Generates a Next.js project
// matching the app's config.
import { NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { loadApp } from '@/lib/appLoader';
import { generateProjectFiles } from '@/lib/export/projectTemplate';
import { slugify } from '@/lib/utils';

export async function POST(req: Request, { params }: { params: { appId: string } }) {
  const r = await loadApp(params.appId, { requireOwner: true });
  if ('error' in r) return NextResponse.json({ error: r.error }, { status: r.status });

  let body: any = {};
  try { body = await req.json(); } catch {}
  const desiredName = slugify(String(body?.repoName ?? r.app.slug));
  const isPrivate = body?.private !== false;

  const session = await getServerSession(authOptions);
  const userToken = (session as any)?.accessToken as string | undefined;
  const token = userToken || process.env.GITHUB_EXPORT_TOKEN;
  if (!token) return NextResponse.json({ error: 'GitHub token not configured. Sign in with GitHub or set GITHUB_EXPORT_TOKEN.' }, { status: 400 });

  const octokit = new Octokit({ auth: token });
  const me = await octokit.users.getAuthenticated();
  const owner = me.data.login;

  const files = generateProjectFiles({ config: r.config, name: r.app.name, slug: r.app.slug });

  let repo;
  try {
    repo = (await octokit.repos.createForAuthenticatedUser({ name: desiredName, private: isPrivate, description: r.app.description ?? `Generated by App Generator`, auto_init: true })).data;
  } catch (e: any) {
    if (e?.status === 422) {
      // Already exists — push anyway
      repo = (await octokit.repos.get({ owner, repo: desiredName })).data as any;
    } else {
      return NextResponse.json({ error: 'GitHub repo create failed', details: e?.message }, { status: 500 });
    }
  }

  // Push files in batches
  for (const f of files) {
    try {
      await octokit.repos.createOrUpdateFileContents({
        owner, repo: desiredName, path: f.path, message: `Add ${f.path}`,
        content: Buffer.from(f.content, 'utf8').toString('base64'),
      });
    } catch (e) {
      console.error('[github export] file failed', f.path, e);
    }
  }

  return NextResponse.json({ url: repo.html_url, owner, repo: desiredName });
}
