// GitHub export: creates a repo with the app's generated code.
import { NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { loadApp } from '@/lib/appLoader';
import { generateProjectFiles } from '@/lib/export/projectTemplate';
import { slugify } from '@/lib/utils';
import { unwrapParams, pickString } from '@/lib/routeParams';

export async function POST(req: Request, ctx: { params: { appId: string } | Promise<{ appId: string }> }) {
  const params = await unwrapParams(ctx.params);
  const appId = pickString(params, 'appId');
  if (!appId) return NextResponse.json({ error: 'Missing appId' }, { status: 400 });
  const r = await loadApp(appId, { requireOwner: true });
  if ('error' in r) return NextResponse.json({ error: r.error }, { status: r.status });

  let body: any = {};
  try { body = await req.json(); } catch {}
  const desiredName = slugify(String(body?.repoName ?? r.app.slug));
  const isPrivate = body?.private !== false;

  const session = await getServerSession(authOptions);
  const userToken = (session as { accessToken?: string } | null)?.accessToken;
  const token = userToken || process.env.GITHUB_EXPORT_TOKEN;
  if (!token) return NextResponse.json({ error: 'GitHub token not configured. Sign in with GitHub or set GITHUB_EXPORT_TOKEN.' }, { status: 400 });

  const octokit = new Octokit({ auth: token });
  let owner = '';
  try {
    const me = await octokit.users.getAuthenticated();
    owner = me.data.login;
  } catch (e) {
    return NextResponse.json({ error: 'GitHub auth failed', details: (e as Error).message }, { status: 401 });
  }

  const files = generateProjectFiles({ config: r.config, name: r.app.name, slug: r.app.slug });

  let repo;
  try {
    repo = (await octokit.repos.createForAuthenticatedUser({ name: desiredName, private: isPrivate, description: r.app.description ?? `Generated by App Generator`, auto_init: true })).data;
  } catch (e: any) {
    if (e?.status === 422) {
      try {
        repo = (await octokit.repos.get({ owner, repo: desiredName })).data as any;
      } catch (e2) {
        return NextResponse.json({ error: 'GitHub repo create failed', details: (e2 as Error).message }, { status: 500 });
      }
    } else {
      return NextResponse.json({ error: 'GitHub repo create failed', details: e?.message }, { status: 500 });
    }
  }

  for (const f of files) {
    try {
      await octokit.repos.createOrUpdateFileContents({
        owner, repo: desiredName, path: f.path, message: `Add ${f.path}`,
        content: Buffer.from(f.content, 'utf8').toString('base64'),
      });
    } catch (e) {
      console.error('[github export] file failed', f.path, e);
    }
  }

  return NextResponse.json({ url: repo.html_url, owner, repo: desiredName });
}
